services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./backend/src:/usr/src/app/src
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  postgres:
    image: docker.io/bitnami/postgresql:15
    restart: always
    environment:
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/bitnami/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  postgres:
    driver: local
